[workspace]
members = [
    "uxi",
    "ataxx"
]

[package]
name = "mexx"
version = "0.1.0"
edition = "2021"

[dependencies]
ataxx = { path = "ataxx" }
uxi = { path = "uxi" }
rand = "0.8.5"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
