[workspace]

[package]
name = "mexx"
version = "0.1.0"
edition = "2021"

[dependencies]
ataxx = { path = "ataxx" }
uxi = { path = "uxi" }
rand = "0.8.5"
goober = { git = 'https://github.com/jw1912/goober.git' }


[profile.release]
opt-level = 3
codegen-units = 1
lto = true
