[workspace]

[package]
name = "mexx"
version = "0.1.0"
edition = "2021"

[dependencies]
ataxx = { path = "ataxx" }
uxi = { path = "uxi" }
derive-new = "0.5"
derive_more = "0.99.18"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
