[package]
name = "mexx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ataxx = { path = "../ataxx" }
uxi = { path = "../uxi" }
rand = "0.8.5"
